# Generated by Django 6.0.2 on 2026-02-17 16:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CmsUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('Cast', 'Cast'), ('Staff', 'Staff'), ('Manager', 'Manager'), ('Admin', 'Admin')], default='Cast', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('first_visit', models.DateField()),
                ('contact_info', models.JSONField()),
                ('preferences', models.JSONField()),
                ('total_spend', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='TTLAND', max_length=255)),
                ('store_type', models.CharField(choices=[('Con Cafe', 'Con Cafe'), ('Bar', 'Bar'), ('Host Club', 'Host Club')], default='Con Cafe', max_length=255)),
                ('address', models.TextField()),
                ('is_active', models.BooleanField()),
            ],
            options={
                'db_table': 'stores',
            },
        ),
        migrations.CreateModel(
            name='CustomerDetail',
            fields=[
                ('customer', models.OneToOneField(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detail', serialize=False, to='api.customer')),
                ('blood_type', models.CharField(max_length=255)),
                ('birthplace', models.CharField(max_length=255)),
                ('appearance_memo', models.TextField()),
                ('company_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('work_location', models.CharField(max_length=255)),
                ('monthly_income', models.IntegerField()),
                ('monthly_drinking_budget', models.IntegerField()),
                ('residence_type', models.CharField(choices=[('Own', 'Own'), ('Rent', 'Rent'), ('Other', 'Other')], max_length=255)),
                ('nearest_station', models.CharField(max_length=255)),
                ('has_lover', models.BooleanField()),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=255)),
                ('children_info', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'customers_detail',
            },
        ),
        migrations.CreateModel(
            name='CustomerPreference',
            fields=[
                ('customer', models.OneToOneField(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='preference', serialize=False, to='api.customer')),
                ('alcohol_strength', models.CharField(choices=[('Weak', 'Weak'), ('Medium', 'Medium'), ('Strong', 'Strong')], max_length=255)),
                ('favorite_food', models.TextField()),
                ('dislike_food', models.TextField()),
                ('hobby', models.TextField()),
                ('favorite_brand', models.TextField()),
            ],
            options={
                'db_table': 'customer_preferences',
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('customer', models.OneToOneField(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='api.customer')),
                ('birthday', models.DateField()),
                ('zodiac', models.CharField(max_length=255)),
                ('animal_fortune', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'customers_profile',
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hourly_wage', models.DecimalField(decimal_places=2, max_digits=8)),
                ('commission_rate', models.FloatField()),
                ('is_on_duty', models.BooleanField()),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='api.cmsuser')),
                ('store', models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='api.store')),
            ],
            options={
                'db_table': 'staff_members',
            },
        ),
        migrations.CreateModel(
            name='PerformanceTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('target_type', models.CharField(choices=[('Daily', 'Daily'), ('Monthly', 'Monthly')], max_length=255)),
                ('target_date', models.DateField()),
                ('staff', models.ForeignKey(db_column='staff_id', on_delete=django.db.models.deletion.CASCADE, related_name='performance_targets', to='api.staffmember')),
            ],
            options={
                'db_table': 'performance_targets',
            },
        ),
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateField()),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_expenses', models.DecimalField(decimal_places=2, max_digits=8)),
                ('labor_costs', models.DecimalField(decimal_places=2, max_digits=8)),
                ('notes', models.TextField()),
                ('store', models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='api.store')),
            ],
            options={
                'db_table': 'daily_summaries',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='store',
            field=models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='api.store'),
        ),
        migrations.CreateModel(
            name='VisitRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visit_date', models.DateField()),
                ('spending', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('PayPay', 'PayPay')], max_length=255)),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField()),
                ('accompanied', models.BooleanField()),
                ('companions', models.CharField(max_length=255)),
                ('memo', models.TextField()),
                ('unpaid_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('received_amount', models.BigIntegerField()),
                ('unpaid_date', models.DateField(db_column='unpaid date')),
                ('receipt', models.BooleanField()),
                ('cast', models.ForeignKey(db_column='cast_id', on_delete=django.db.models.deletion.CASCADE, related_name='visit_records', to='api.staffmember')),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='visit_records', to='api.customer')),
            ],
            options={
                'db_table': 'visit_records',
            },
        ),
    ]
