# Generated by Django 6.0.2 on 2026-03-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_visitrecord_optional_memo_unpaid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitrecord',
            name='spending',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='visitrecord',
            name='unpaid_amount',
            field=models.BigIntegerField(),
        ),
    ]
