# Generated by Django 6.0.2 on 2026-03-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_visitrecord_spending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsuser',
            name='viewable_stores',
            field=models.ManyToManyField(blank=True, db_table='user_viewable_stores', related_name='viewable_by_users', to='api.store'),
        ),
        migrations.AlterField(
            model_name='cmsuser',
            name='role',
            field=models.CharField(choices=[('Cast', 'Cast'), ('Staff', 'Staff'), ('Manager', 'Manager'), ('Supervisor', 'Supervisor'), ('Admin', 'Admin'), ('Owner', 'Owner')], default='Cast', max_length=255),
        ),
    ]
