# Generated by Django 6.0.2 on 2026-03-17 00:29

import api.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_viewable_stores_to_cmsuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField(help_text='前借希望金額（円）')),
                ('status', models.CharField(choices=[('Pending', '申請中'), ('Approved', '承認'), ('Rejected', '却下')], default='Pending', max_length=32)),
                ('memo', models.TextField(blank=True, default='')),
                ('attachment', models.FileField(blank=True, help_text='前借伝票の添付', null=True, upload_to=api.models.advance_slip_upload_to)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='advance_requests', to='api.cmsuser')),
            ],
            options={
                'db_table': 'advance_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
