# Generated by Django 6.0.2 on 2026-03-17 14:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_advance_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('Daily', 'Daily'), ('Monthly', 'Monthly')], max_length=255)),
                ('target_date', models.DateField()),
                ('sales_target', models.BigIntegerField(default=0)),
                ('group_target', models.BigIntegerField(default=0)),
                ('new_sales_target', models.BigIntegerField(default=0)),
                ('new_group_target', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.CASCADE, related_name='store_targets', to='api.store')),
            ],
            options={
                'db_table': 'store_targets',
                'constraints': [models.UniqueConstraint(fields=('store', 'target_type', 'target_date'), name='uniq_store_target_per_period')],
            },
        ),
    ]
