# Generated by Django 6.0.2 on 2026-03-23 01:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_store_targets'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateField()),
                ('content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_reports_created', to='api.cmsuser')),
                ('store', models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='api.store')),
            ],
            options={
                'db_table': 'daily_reports',
                'ordering': ['-report_date', 'store_id'],
                'constraints': [models.UniqueConstraint(fields=('store', 'report_date'), name='uniq_daily_report_store_date')],
            },
        ),
    ]
