# Generated by Django 6.0.2 on 2026-03-25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_add_store_targets"),
    ]

    operations = [
        migrations.CreateModel(
            name="HostSalarySetting",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tax_rate", models.DecimalField(decimal_places=4, default=0.1, max_digits=6)),
                ("service_rate", models.DecimalField(decimal_places=4, default=0.2, max_digits=6)),
                (
                    "rounding_mode",
                    models.CharField(
                        choices=[("Round", "Round"), ("Floor", "Floor"), ("Ceil", "Ceil")],
                        default="Round",
                        max_length=255,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.OneToOneField(
                        db_column="store_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="host_salary_setting",
                        to="api.store",
                    ),
                ),
            ],
            options={
                "db_table": "host_salary_settings",
            },
        ),
    ]

