# Generated by Django 6.0.2 on 2026-03-25 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_daily_report'),
        ('api', '0009_add_host_salary_settings'),
    ]

    operations = [
    ]
