# Generated by Django 6.0.2 on 2026-03-25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_merge_20260325_0825"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalLedgerEntry",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("entry_date", models.DateField()),
                ("entry_type", models.CharField(choices=[("Income", "Income"), ("Expense", "Expense")], max_length=255)),
                ("amount", models.BigIntegerField()),
                ("category", models.CharField(blank=True, default="", max_length=255)),
                ("memo", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_ledger_entries",
                        to="api.cmsuser",
                    ),
                ),
            ],
            options={
                "db_table": "personal_ledger_entries",
                "ordering": ["-entry_date", "-created_at"],
            },
        ),
    ]

